/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '1/9/25, 9:41 PM' 
 * Generated by 'u63773492' 
 * Generated on server 'ODAWS01-USW2-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 5.14.0-284.30.1.el9_2.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-05%253A00&ticket=ST-144865-4PnZKwhafxTaYxKa1gep-cas' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc corr data=WORK.'REVENUE VS. LAYOFF'n pearson nosimple noprob plots=none;
	var 'No. of layoff'n;
	with 'Annual % Change'n;
run;